language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install: 
    - "pip install -r requirements.txt -r requirements-tests.txt --use-mirrors"
    - "if [[ ${TRAVIS_PYTHON_VERSION::1} != '3' ]]; then pip install -r requirements-py2.txt --use-mirrors; fi"
script: "nosetests"
